In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


In [10]:
df = pd.read_csv(r'D:\19501a1295\mini project\healthcare-dataset-stroke-data.csv')

In [11]:
df

id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes   
1     51676  Female  61.0             0              0          Yes   
2     31112    Male  80.0             0              1          Yes   
3     60182  Female  49.0             0              0          Yes   
4      1665  Female  79.0             1              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5105  18234  Female  80.0             1              0          Yes   
5106  44873  Female  81.0             0              0          Yes   
5107  19723  Female  35.0             0              0          Yes   
5108  37544    Male  51.0             0              0          Yes   
5109  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
1     Self-employed          Rural             202.21   NaN     never smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
...             ...            ...                ...   ...              ...   
5105        Private          Urban              83.75   NaN     never smoked   
5106  Self-employed          Urban             125.20  40.0     never smoked   
5107  Self-employed          Rural              82.99  30.6     never smoked   
5108        Private          Rural             166.29  25.6  formerly smoked   
5109       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
5105       0  
5106       0  
5107       0  
5108       0  
5109       0  

[5110 rows x 12 columns]

In [12]:
df.shape

(5110, 12)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 5110 non-null   int64  
 1   gender             5110 non-null   object 
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64  
 4   heart_disease      5110 non-null   int64  
 5   ever_married       5110 non-null   object 
 6   work_type          5110 non-null   object 
 7   Residence_type     5110 non-null   object 
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object 
 11  stroke             5110 non-null   int64  
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB


In [14]:
df.describe()

id          age  hypertension  heart_disease  \
count   5110.000000  5110.000000   5110.000000    5110.000000   
mean   36517.829354    43.226614      0.097456       0.054012   
std    21161.721625    22.612647      0.296607       0.226063   
min       67.000000     0.080000      0.000000       0.000000   
25%    17741.250000    25.000000      0.000000       0.000000   
50%    36932.000000    45.000000      0.000000       0.000000   
75%    54682.000000    61.000000      0.000000       0.000000   
max    72940.000000    82.000000      1.000000       1.000000   

       avg_glucose_level          bmi       stroke  
count        5110.000000  4909.000000  5110.000000  
mean          106.147677    28.893237     0.048728  
std            45.283560     7.854067     0.215320  
min            55.120000    10.300000     0.000000  
25%            77.245000    23.500000     0.000000  
50%            91.885000    28.100000     0.000000  
75%           114.090000    33.100000     0.000000  
max           271.740000    97.600000     1.000000

In [15]:
df.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [16]:
df['bmi']

0       36.6
1        NaN
2       32.5
3       34.4
4       24.0
        ... 
5105     NaN
5106    40.0
5107    30.6
5108    25.6
5109    26.2
Name: bmi, Length: 5110, dtype: float64

In [17]:
df['bmi'].value_counts()

28.7    41
28.4    38
26.7    37
27.6    37
26.1    37
        ..
48.7     1
49.2     1
51.0     1
49.4     1
14.9     1
Name: bmi, Length: 418, dtype: int64

In [18]:
df['bmi'].describe()

count    4909.000000
mean       28.893237
std         7.854067
min        10.300000
25%        23.500000
50%        28.100000
75%        33.100000
max        97.600000
Name: bmi, dtype: float64

In [19]:
df['bmi'].fillna(df['bmi'].mean(),inplace =True)

In [20]:
df['bmi'].describe()

count    5110.000000
mean       28.893237
std         7.698018
min        10.300000
25%        23.800000
50%        28.400000
75%        32.800000
max        97.600000
Name: bmi, dtype: float64

In [21]:
df.isnull().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [22]:
df.drop('id',axis=1,inplace=True)

In [23]:
df

gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0             0              1          Yes        Private   
1     Female  61.0             0              0          Yes  Self-employed   
2       Male  80.0             0              1          Yes        Private   
3     Female  49.0             0              0          Yes        Private   
4     Female  79.0             1              0          Yes  Self-employed   
...      ...   ...           ...            ...          ...            ...   
5105  Female  80.0             1              0          Yes        Private   
5106  Female  81.0             0              0          Yes  Self-employed   
5107  Female  35.0             0              0          Yes  Self-employed   
5108    Male  51.0             0              0          Yes        Private   
5109  Female  44.0             0              0          Yes       Govt_job   

     Residence_type  avg_glucose_level        bmi   smoking_status  stroke  
0             Urban             228.69  36.600000  formerly smoked       1  
1             Rural             202.21  28.893237     never smoked       1  
2             Rural             105.92  32.500000     never smoked       1  
3             Urban             171.23  34.400000           smokes       1  
4             Rural             174.12  24.000000     never smoked       1  
...             ...                ...        ...              ...     ...  
5105          Urban              83.75  28.893237     never smoked       0  
5106          Urban             125.20  40.000000     never smoked       0  
5107          Rural              82.99  30.600000     never smoked       0  
5108          Rural             166.29  25.600000  formerly smoked       0  
5109          Urban              85.28  26.200000          Unknown       0  

[5110 rows x 11 columns]

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   gender             5110 non-null   object 
 1   age                5110 non-null   float64
 2   hypertension       5110 non-null   int64  
 3   heart_disease      5110 non-null   int64  
 4   ever_married       5110 non-null   object 
 5   work_type          5110 non-null   object 
 6   Residence_type     5110 non-null   object 
 7   avg_glucose_level  5110 non-null   float64
 8   bmi                5110 non-null   float64
 9   smoking_status     5110 non-null   object 
 10  stroke             5110 non-null   int64  
dtypes: float64(3), int64(3), object(5)
memory usage: 439.3+ KB


In [25]:
df['avg_glucose_level'].describe()

count    5110.000000
mean      106.147677
std        45.283560
min        55.120000
25%        77.245000
50%        91.885000
75%       114.090000
max       271.740000
Name: avg_glucose_level, dtype: float64

In [26]:
df['avg_glucose_level'].value_counts()

93.88     6
91.68     5
91.85     5
83.16     5
73.00     5
         ..
111.93    1
94.40     1
95.57     1
66.29     1
85.28     1
Name: avg_glucose_level, Length: 3979, dtype: int64

In [27]:
df.head()

gender   age  hypertension  heart_disease ever_married      work_type  \
0    Male  67.0             0              1          Yes        Private   
1  Female  61.0             0              0          Yes  Self-employed   
2    Male  80.0             0              1          Yes        Private   
3  Female  49.0             0              0          Yes        Private   
4  Female  79.0             1              0          Yes  Self-employed   

  Residence_type  avg_glucose_level        bmi   smoking_status  stroke  
0          Urban             228.69  36.600000  formerly smoked       1  
1          Rural             202.21  28.893237     never smoked       1  
2          Rural             105.92  32.500000     never smoked       1  
3          Urban             171.23  34.400000           smokes       1  
4          Rural             174.12  24.000000     never smoked       1

In [28]:
df['work_type'].unique()


array(['Private', 'Self-employed', 'Govt_job', 'children', 'Never_worked'],
      dtype=object)

In [29]:
df['smoking_status'].unique()

array(['formerly smoked', 'never smoked', 'smokes', 'Unknown'],
      dtype=object)

In [30]:
df['Residence_type'].unique()

array(['Urban', 'Rural'], dtype=object)

In [31]:
df['ever_married'].unique()

array(['Yes', 'No'], dtype=object)

In [32]:
df['gender'].unique()

array(['Male', 'Female', 'Other'], dtype=object)

In [33]:
from sklearn.preprocessing import LabelEncoder
enc=LabelEncoder()

In [34]:
gender=enc.fit_transform(df['gender'])
gender

array([1, 0, 1, ..., 0, 1, 0])

In [35]:
smoking_status=enc.fit_transform(df['smoking_status'])
smoking_status

array([1, 2, 2, ..., 2, 1, 0])

In [36]:
work_type=enc.fit_transform(df['work_type'])
work_type

array([2, 3, 2, ..., 3, 2, 0])

In [37]:
Residence_type=enc.fit_transform(df['Residence_type'])
Residence_type

array([1, 0, 0, ..., 0, 0, 1])

In [38]:
ever_married=enc.fit_transform(df['ever_married'])
ever_married

array([1, 1, 1, ..., 1, 1, 1])

In [39]:
df['work_type']=work_type
df['gender']=gender
df['ever_married']=ever_married
df['smoking_status']=smoking_status
df['Residence_type']=Residence_type
df

gender   age  hypertension  heart_disease  ever_married  work_type  \
0          1  67.0             0              1             1          2   
1          0  61.0             0              0             1          3   
2          1  80.0             0              1             1          2   
3          0  49.0             0              0             1          2   
4          0  79.0             1              0             1          3   
...      ...   ...           ...            ...           ...        ...   
5105       0  80.0             1              0             1          2   
5106       0  81.0             0              0             1          3   
5107       0  35.0             0              0             1          3   
5108       1  51.0             0              0             1          2   
5109       0  44.0             0              0             1          0   

      Residence_type  avg_glucose_level        bmi  smoking_status  stroke  
0                  1             228.69  36.600000               1       1  
1                  0             202.21  28.893237               2       1  
2                  0             105.92  32.500000               2       1  
3                  1             171.23  34.400000               3       1  
4                  0             174.12  24.000000               2       1  
...              ...                ...        ...             ...     ...  
5105               1              83.75  28.893237               2       0  
5106               1             125.20  40.000000               2       0  
5107               0              82.99  30.600000               2       0  
5108               0             166.29  25.600000               1       0  
5109               1              85.28  26.200000               0       0  

[5110 rows x 11 columns]

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   gender             5110 non-null   int32  
 1   age                5110 non-null   float64
 2   hypertension       5110 non-null   int64  
 3   heart_disease      5110 non-null   int64  
 4   ever_married       5110 non-null   int32  
 5   work_type          5110 non-null   int32  
 6   Residence_type     5110 non-null   int32  
 7   avg_glucose_level  5110 non-null   float64
 8   bmi                5110 non-null   float64
 9   smoking_status     5110 non-null   int32  
 10  stroke             5110 non-null   int64  
dtypes: float64(3), int32(5), int64(3)
memory usage: 339.5 KB


In [41]:
X=df.drop('stroke',axis=1)
X

gender   age  hypertension  heart_disease  ever_married  work_type  \
0          1  67.0             0              1             1          2   
1          0  61.0             0              0             1          3   
2          1  80.0             0              1             1          2   
3          0  49.0             0              0             1          2   
4          0  79.0             1              0             1          3   
...      ...   ...           ...            ...           ...        ...   
5105       0  80.0             1              0             1          2   
5106       0  81.0             0              0             1          3   
5107       0  35.0             0              0             1          3   
5108       1  51.0             0              0             1          2   
5109       0  44.0             0              0             1          0   

      Residence_type  avg_glucose_level        bmi  smoking_status  
0                  1             228.69  36.600000               1  
1                  0             202.21  28.893237               2  
2                  0             105.92  32.500000               2  
3                  1             171.23  34.400000               3  
4                  0             174.12  24.000000               2  
...              ...                ...        ...             ...  
5105               1              83.75  28.893237               2  
5106               1             125.20  40.000000               2  
5107               0              82.99  30.600000               2  
5108               0             166.29  25.600000               1  
5109               1              85.28  26.200000               0  

[5110 rows x 10 columns]

In [42]:
Y=df['stroke']
Y

0       1
1       1
2       1
3       1
4       1
       ..
5105    0
5106    0
5107    0
5108    0
5109    0
Name: stroke, Length: 5110, dtype: int64

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.2,random_state=None)
X_train

gender   age  hypertension  heart_disease  ever_married  work_type  \
1346       1  49.0             0              0             1          2   
235        0  68.0             0              0             1          2   
1624       1  51.0             0              0             1          2   
91         1  81.0             0              0             1          2   
1871       1  56.0             1              0             1          0   
...      ...   ...           ...            ...           ...        ...   
1297       0  79.0             0              0             0          3   
1939       0  33.0             0              0             1          0   
993        1  64.0             0              0             1          2   
2520       1  26.0             0              0             0          3   
4780       0  48.0             0              0             1          2   

      Residence_type  avg_glucose_level   bmi  smoking_status  
1346               1             199.96  28.6               2  
235                0             211.06  39.3               0  
1624               1              66.11  26.3               2  
91                 1              72.81  26.3               2  
1871               1              72.79  23.8               3  
...              ...                ...   ...             ...  
1297               0              71.98  36.4               2  
1939               0              57.92  22.3               0  
993                0              84.27  24.6               0  
2520               1             200.28  31.9               1  
4780               0             114.92  29.2               0  

[4088 rows x 10 columns]

In [44]:
X_test

gender    age  hypertension  heart_disease  ever_married  work_type  \
3705       1   1.08             0              0             0          4   
977        0   7.00             0              0             0          4   
4930       1   9.00             0              0             0          4   
3775       0  63.00             0              0             1          2   
560        1  12.00             0              0             0          4   
...      ...    ...           ...            ...           ...        ...   
941        1  60.00             0              0             1          0   
673        0  58.00             0              0             1          0   
3941       0  32.00             0              0             1          2   
3613       0  76.00             1              0             1          3   
315        1  57.00             0              1             1          2   

      Residence_type  avg_glucose_level        bmi  smoking_status  
3705               0              74.50  28.893237               0  
977                1              86.75  22.300000               0  
4930               1              84.40  14.900000               0  
3775               1              83.74  21.400000               0  
560                1              67.06  16.100000               0  
...              ...                ...        ...             ...  
941                1             100.54  30.100000               2  
673                0              77.46  27.600000               2  
3941               0              67.10  27.100000               0  
3613               1              78.70  27.600000               1  
315                0              62.20  31.000000               1  

[1022 rows x 10 columns]

In [45]:
Y_train

1346    0
235     1
1624    0
91      1
1871    0
       ..
1297    0
1939    0
993     0
2520    0
4780    0
Name: stroke, Length: 4088, dtype: int64

In [46]:
Y_test

3705    0
977     0
4930    0
3775    0
560     0
       ..
941     0
673     0
3941    0
3613    0
315     0
Name: stroke, Length: 1022, dtype: int64

In [47]:
df.describe()

gender          age  hypertension  heart_disease  ever_married  \
count  5110.000000  5110.000000   5110.000000    5110.000000   5110.000000   
mean      0.414286    43.226614      0.097456       0.054012      0.656164   
std       0.493044    22.612647      0.296607       0.226063      0.475034   
min       0.000000     0.080000      0.000000       0.000000      0.000000   
25%       0.000000    25.000000      0.000000       0.000000      0.000000   
50%       0.000000    45.000000      0.000000       0.000000      1.000000   
75%       1.000000    61.000000      0.000000       0.000000      1.000000   
max       2.000000    82.000000      1.000000       1.000000      1.000000   

         work_type  Residence_type  avg_glucose_level          bmi  \
count  5110.000000     5110.000000        5110.000000  5110.000000   
mean      2.167710        0.508023         106.147677    28.893237   
std       1.090293        0.499985          45.283560     7.698018   
min       0.000000        0.000000          55.120000    10.300000   
25%       2.000000        0.000000          77.245000    23.800000   
50%       2.000000        1.000000          91.885000    28.400000   
75%       3.000000        1.000000         114.090000    32.800000   
max       4.000000        1.000000         271.740000    97.600000   

       smoking_status       stroke  
count     5110.000000  5110.000000  
mean         1.376908     0.048728  
std          1.071534     0.215320  
min          0.000000     0.000000  
25%          0.000000     0.000000  
50%          2.000000     0.000000  
75%          2.000000     0.000000  
max          3.000000     1.000000

In [48]:
from sklearn.preprocessing import StandardScaler
std=StandardScaler()

In [49]:
X_train_std=std.fit_transform(X_train)
X_test_std=std.fit_transform(X_test)

In [50]:
import pickle
import os

In [51]:
scaler_path=os.path.join('D:/19501a1295/','mini project/scaler.pkl')
with open(scaler_path,'wb') as scaler_file:
    pickle.dump(std,scaler_file)

In [52]:
X_train_std

array([[ 1.19299477,  0.25429899, -0.32978858, ...,  2.03916992,
        -0.04850122,  0.57945022],
       [-0.83822664,  1.09173123, -0.32978858, ...,  2.28138493,
         1.32030654, -1.27842626],
       [ 1.19299477,  0.34244975, -0.32978858, ..., -0.88159399,
        -0.34273093,  0.57945022],
       ...,
       [ 1.19299477,  0.91542971, -0.32978858, ..., -0.4853215 ,
        -0.56020506, -1.27842626],
       [ 1.19299477, -0.75943477, -0.32978858, ...,  2.0461527 ,
         0.37365444, -0.34948802],
       [-0.83822664,  0.21022361, -0.32978858, ...,  0.18349743,
         0.02825435, -1.27842626]])

In [53]:
X_test_std

array([[ 1.16866489, -1.88966418, -0.32382845, ..., -0.70242047,
         0.04780035, -1.31281957],
       [-0.84886132, -1.62414364, -0.32382845, ..., -0.4174508 ,
        -0.86944528, -1.31281957],
       [ 1.16866489, -1.53444075, -0.32382845, ..., -0.47211845,
        -1.89892712, -1.31281957],
       ...,
       [-0.84886132, -0.50285754, -0.32382845, ..., -0.87456541,
        -0.20167328, -1.31281957],
       [-0.84886132,  1.470606  ,  3.0880548 , ..., -0.60471658,
        -0.13211369, -0.36125815],
       [ 1.16866489,  0.61842856, -0.32382845, ..., -0.98855328,
         0.34089148, -0.36125815]])

In [54]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [55]:
rf.fit(X_train_std,Y_train)

RandomForestClassifier()

In [56]:
rf.feature_importances_

array([0.03013661, 0.23032241, 0.02579533, 0.02517456, 0.01763643,
       0.0512075 , 0.03291149, 0.2837919 , 0.23466835, 0.06835541])

In [57]:
X_train.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status'],
      dtype='object')

In [58]:
prediction=rf.predict(X_test_std)

In [59]:
Y_test

3705    0
977     0
4930    0
3775    0
560     0
       ..
941     0
673     0
3941    0
3613    0
315     0
Name: stroke, Length: 1022, dtype: int64

In [60]:
from sklearn.metrics import accuracy_score
rf_accuracy=accuracy_score(Y_test,prediction)
rf_accuracy

0.9579256360078278

In [61]:
import joblib
model_path=os.path.join('D:/19501a1295/','mini project/rf.sav')
joblib.dump(rf,model_path)

['D:/19501a1295/mini project/rf.sav']

In [62]:
from sklearn.tree import  DecisionTreeClassifier
dt=DecisionTreeClassifier()

In [63]:
dt.fit(X_train_std,Y_train)

DecisionTreeClassifier()

In [64]:
dt.fit(X_train_std,Y_train)

DecisionTreeClassifier()

In [65]:
dt.feature_importances_

array([0.01709577, 0.21811903, 0.03773156, 0.0169016 , 0.02115404,
       0.04588985, 0.02733501, 0.3549295 , 0.1901834 , 0.07066024])

In [66]:
X_train.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status'],
      dtype='object')

In [67]:
prediction1=dt.predict(X_test_std)

In [68]:
Y_test

3705    0
977     0
4930    0
3775    0
560     0
       ..
941     0
673     0
3941    0
3613    0
315     0
Name: stroke, Length: 1022, dtype: int64

In [69]:
from sklearn.metrics import accuracy_score
dt_accuracy=accuracy_score(Y_test,prediction1)
dt_accuracy

0.9197651663405088

In [70]:
import pickle
filename = r'C:\mini project\final_model.sav'
pickle.dump(rf,open(filename, 'wb'))